name: Deploy Fake
on:
   workflow_call:
       inputs:
           ambiente:
              type: string
              default: "desenvolvimento"
              description: "Ambiente aonde vai ser feito o deploy "
       secrets:
           password:
              required: true
              description: "Ambiente Secret aonde vai ser feito o deploy "
                    
jobs:
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
           - name: Deploy no ambiente
             run: echo "Executando deploy no ambiente ${{ inputs.ambiente }}  password  ${{ secrets.password }}    "