name: CI/CD Fake
on: 
    workflow_dispatch:  
      inputs:
        ambiente:
            type: choice
            default: "desenvolvimento"
            description: "Ambiente aonde vai ser feito o deploy "
            options:
              - desenvolvimento
              - homologacao
              - producao       
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Build de Imagem Docker
        run: echo "Execução do comando de docker build "
      - name: Execução de Testes de Software
        run: echo "Aqui eu executo o teste de software "
      - name: Publicando a Release
        run: echo "Publicação da Relase final"
  CD:
   needs: [CI]
   uses: jceleste1/GitActionsReaprovWorkflows/.github/workflows/cd.yml@main
   with:
     ambiente: ${{  inputs.ambiente }}
   secrets:
     ambiente_secrets: ${{  secrets.AMBIENTE_ENTREGA }}

